# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      # Install Simple 2D
      - run: wget https://raw.githubusercontent.com/simple2d/simple2d/master/bin/simple2d.sh
      - run: bash simple2d.sh install -y

      # Build and test gem
      - run: bundle install
      - run: rake

      # Test native
      - run: ruby2d build --native test/ci-build.rb
      - run: ./build/app
