# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Update Homebrew and tap Simple 2D
      - run: brew update
      - run: brew tap simple2d/tap
      - run: brew install simple2d mruby

      # Build and test gem
      - run: rake

      # Test native
      - run: ruby2d build --native test/ci-build.rb
      - run: ./build/app

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

